# Done to increase the memory available to gradle.
name=Some Translation Fixes

org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# More versions available at: https://legacyfabric.net/usage.html
minecraft_version=1.6.4
yarn_build=604
loader_version=0.18.4
loom_version=1.15.3

# Mod Properties
mod_version=1.0.0-standalone
maven_group=com.msg
archives_base_name=some-translation-fixes

# Dependencies
# Legacy Fabric API
# Check availability for your MC version at https://legacyfabric.net/usage.html
fabric_version=1.13.3+1.6.4